# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AuthPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AuthPageUI(object):
    def setupUi(self, AuthPageUI):
        AuthPageUI.setObjectName("AuthPageUI")
        AuthPageUI.resize(845, 407)
        self.centralwidget = QtWidgets.QWidget(AuthPageUI)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 130, 471, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PasswordEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PasswordEdit.sizePolicy().hasHeightForWidth())
        self.PasswordEdit.setSizePolicy(sizePolicy)
        self.PasswordEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PasswordEdit.setAutoFillBackground(False)
        self.PasswordEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.horizontalLayout.addWidget(self.PasswordEdit)
        self.AuthButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AuthButton.sizePolicy().hasHeightForWidth())
        self.AuthButton.setSizePolicy(sizePolicy)
        self.AuthButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AuthButton.setFlat(False)
        self.AuthButton.setObjectName("AuthButton")
        self.horizontalLayout.addWidget(self.AuthButton)
        self.ResetButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetButton.sizePolicy().hasHeightForWidth())
        self.ResetButton.setSizePolicy(sizePolicy)
        self.ResetButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ResetButton.setObjectName("ResetButton")
        self.horizontalLayout.addWidget(self.ResetButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        AuthPageUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(AuthPageUI)
        QtCore.QMetaObject.connectSlotsByName(AuthPageUI)

    def retranslateUi(self, AuthPageUI):
        _translate = QtCore.QCoreApplication.translate
        AuthPageUI.setWindowTitle(_translate("AuthPageUI", "Encrypted Notepad | Authentication"))
        self.PasswordEdit.setPlaceholderText(_translate("AuthPageUI", "Password"))
        self.AuthButton.setText(_translate("AuthPageUI", "Authentication"))
        self.AuthButton.setShortcut(_translate("AuthPageUI", "Return"))
        self.ResetButton.setText(_translate("AuthPageUI", "Reset password"))
